version: '3'

services:
  nginx-rtmp:
    build: .
    ports:
      - 1935:1935
      - 8080:80
      - 443:443
    volumes:
            - /etc/letsencrypt:/opt/certs
            - /var/log/ooftv-docker:/var/log
            - /var/www/html:/usr/local/nginx/html
            - /home/ooftv/Documents/github/ooftv-docker-nginx-rtmp/nginx.conf:/etc/nginx/nginx.conf:ro
